

INSERT INTO produto (produto, VALOR_COMPRA   , VALOR_VENDA  ) VALUES ('Coca_Cola', '3.50' ,'5.00');
INSERT INTO produto (produto, VALOR_COMPRA   , VALOR_VENDA  ) VALUES ('Agua', '2.50' ,'3.00');
INSERT INTO produto (produto, VALOR_COMPRA   , VALOR_VENDA  ) VALUES ('Carveja', '3.75' ,'5.00');
INSERT INTO produto (produto, VALOR_COMPRA   , VALOR_VENDA  ) VALUES ('Heineken', '4.50' ,'8.00');


INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Binho', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Binho', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Binho', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Binho', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Binho', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Dori', 30, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marcao', 80, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Decio', 75, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('PP', 23, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Paulo', 40, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marola', 50, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Marolinha', 60, '2024-03-15', false);
INSERT INTO comanda(cliente, valor, data, pago) VALUES ('Celio', 40, '2024-03-15', false);

INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 1 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );
INSERT INTO COMANDAPRODUTO  ( ID_COMANDA , IDPRODUTO   ) VALUES ( 2 ,  3 );

INSERT INTO CONTA (conta, valor, data, pago) VALUES ('Energia', 50 , '2024-03-01', false);
INSERT INTO CONTA (conta, valor, data, pago) VALUES ('Agua', 35 , '2024-03-01', false);
INSERT INTO CONTA (conta, valor, data, pago) VALUES ('Carvão', 60 , '2024-03-01', false);
INSERT INTO CONTA (conta, valor, data, pago) VALUES ('Aluguel', 600 , '2024-03-01', false);
INSERT INTO CONTA (conta, valor, data, pago) VALUES ('Carne', 100 , '2024-03-01', false);
INSERT INTO CONTA (conta, valor, data, pago) VALUES ('cerveja', 800 , '2024-03-01', false);

